# Generated by Django 3.1.4 on 2020-12-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('varsity_id', models.IntegerField(unique=True)),
                ('phone', models.IntegerField()),
                ('address', models.TextField(max_length=200)),
                ('email', models.CharField(max_length=40, unique=True)),
            ],
        ),
    ]
