# Generated by Django 3.1.4 on 2020-12-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='varsity_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
